'''
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

# Returns the sum of the even-valued Fibonnaci sequence values that do not exceed four million
def evenSumFibonnaci(target):
    cur = 2
    prev = 1
    sum = 0
    while cur < target:
        if cur % 2 == 0:
            sum += cur
        tmp = cur
        cur = cur + prev
        prev = tmp
    return sum

if __name__ == "__main__":
    target = 4e6
    print(evenSumFibonnaci(target))